### ISSUE TITLE
Error preprocessing data for TabFact

### ISSUE THREAD

**Issue by vnik18** [microsoft/Table-Pretraining#10]
Hi, thank you for sharing your code! I am trying to run your trained model `tapex.large` on TabFact's test set, and I am pre-processing the file `test.jsonl` for that. When I run the file `python process_tabfact_data.py` to do this pre-processing, I get the following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'tapex.large/dict.src.txt'`

I downloaded your preprocessed data from this link (https://github.com/microsoft/Table-Pretraining/releases/download/preprocessed-data/tabfact.preprocessed.zip) but I did not find this file `tapex.large/dict.src.txt` anywhere. 

Could you please help me solve this? Thank you very much!

**Comment by SivilTaram** [comment]
@vnik18 Hi, thanks for your interest on our work! Have you downloaded the `tapex.large` checkpoint and unzip it? Thanks.

**Comment by vnik18** [comment]
@SivilTaram Thank you for the prompt response! Yes I have, and it has a file named `'dict.txt'`. Is this file the same as the `'dict.src.txt'` mentioned in the error?

**Comment by SivilTaram** [comment]
@vnik18 Right, it is! You could copy it into `dict.src.txt` (which should be performed if you use our automatic downloading code) to solve the problem.

**Comment by vnik18** [comment]
@SivilTaram Thank you! I am able to run the model now. However, I am seeing some strange behavior in this line: https://github.com/microsoft/Table-Pretraining/blob/main/examples/tableft/run_model.py#L136

The prediction output for the TabFact data should be either 0 or 1 for a sentence input, but this line gives other outputs as well, which are not 0 or 1 (e.g. `'13'`, '`262'` etc). This is also reducing the accuracy of the model on the TabFact test data. 

Please let me know if I am missing something here?

**Comment by SivilTaram** [comment]
@vnik18 It is strange, let me check if my side works well.

**Comment by SivilTaram** [comment]
@vnik18 Hi, I find the problem. Do you try to evaluate the `tapex.large` instead of `tapex.large.tabfact` on the tabfact dataset? Note that the `tapex.large` is the one which is not fine-tuned on the TabFact dataset. You may download the fine-tuned one to evaluate.

**Comment by vnik18** [comment]
@SivilTaram Do you mean the model that I am passing to `args.model_dir` argument? I am using the fine-tuned `tapex.large.tabfact` for that, but I still get the error that I mentioned above

EDIT: 
This is the command I am using for testing: 

`python run_model.py eval --dataset-dir proc_dataset/tabfact/tapex.large --model-dir tapex.large.tabfact `

And this is the output I get: 

```
2021-12-02 17:10:43 | INFO | fairseq.file_utils | loading archive file tapex.large.tabfact
2021-12-02 17:10:43 | INFO | fairseq.file_utils | loading archive file proc_dataset/tabfact/tapex.large

2021-12-02 17:10:44 | INFO | fairseq.tasks.sentence_prediction | [input] dictionary: 50265 types
2021-12-02 17:10:44 | INFO | fairseq.tasks.sentence_prediction | [label] dictionary: 50265 types
2021-12-02 17:10:55 | INFO | fairseq.models.bart.model | Registering classification head: sentence_classification_head
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 12779/12779 [11:18<00:00, 18.84it/s]
2021-12-02 17:22:18 | INFO | __main__ | ====================evaluate on test====================
2021-12-02 17:22:18 | INFO | __main__ | {"total": 12779, "correct": 0, "acc": 0.0}
```

**Comment by SivilTaram** [comment]
@vnik18 Sorry to hear that. Do you mind showing the file structure under the folder `proc_dataset/tabfact/tapex.large` ? The one in my side is as below:
![image](https://user-images.githubusercontent.com/10275209/144531553-8b9acf52-eb91-4b7d-8100-6344f229e0cf.png)

And, the folder `tapex.large.tabfact` contains the following files:
![image](https://user-images.githubusercontent.com/10275209/144531632-92293346-5337-413b-a81d-360f1bb78f0b.png)

**Comment by vnik18** [comment]
@SivilTaram Sure, please find the file structure below for both directories: 

```
tapex.large.tabfact
├── encoder.json
├── model.pt
└── vocab.bpe
```

and

```
proc_dataset/tabfact/
├── dict.txt
├── input0
│   ├── dict.txt
│   ├── preprocess.log
│   ├── test.bin
│   ├── test.idx
│   ├── train.bin
│   └── train.idx
├── label
│   ├── dict.txt
│   ├── preprocess.log
│   ├── test.bin
│   ├── test.idx
│   ├── train.bin
│   ├── train.idx
│   ├── valid.bin
│   └── valid.idx
├── tapex.large
│   ├── input0
│   │   ├── dict.txt
│   │   ├── preprocess.log
│   │   ├── test.bin
│   │   ├── test.idx
│   │   ├── train.bin
│   │   └── train.idx
│   ├── label
│   │   ├── dict.txt
│   │   ├── preprocess.log
│   │   ├── test.bin
│   │   ├── test.idx
│   │   ├── train.bin
│   │   ├── train.idx
│   │   ├── valid.bin
│   │   └── valid.idx
│   ├── test.input0
│   ├── test.label
│   └── test.raw.input0
├── test.input0
├── test.label
├── test.raw.input0
├── train.input0
├── train.label
├── train.raw.input0
├── valid.input0
├── valid.label
└── valid.raw.input0

```

**Comment by SivilTaram** [comment]
@vnik18 Thank you for the detailed demonstration! The file structure seems well for me. From the error log from your previous comment, I guess the error is because of the file `proc_dataset/tabfact/tapex.large/label/dict.txt`.

Could you check that file? It should be as below:
```
1 45435 
0 36974 
madeupword0000 0 
madeupword0001 0 
```

If not, could you try to replace it with the pasted one? It should work.

BTW, I have tried to reproduce the whole procedure from scratch but do not encounter the same problem. Hope the above solution can temporally solve your problem.

**Comment by vnik18** [comment]
@SivilTaram Thank you so much for all your help! I really appreciate all your prompt and detailed responses in helping me debug the code. 

Replacing `proc_dataset/tabfact/tapex.large/label/dict.txt` with the file you pasted above worked. 

A quick question: Can you tell me how this file was created, and how it would change if I train and test your model on a different dataset? I just want to make sure this error doesn't repeat again, since I'm not sure how it happened in the first place.

**Comment by SivilTaram** [comment]
@vnik18 Glad to hear that your problem is solved! Sure I can explain more details:
- The file `dict.txt` is created by the library `fairseq` when we run the command `fairseq-preprocess` (i.e., corresponding to the function `fairseq_binary_classification` in the `run_model.py`).
- The whole pre-processing procedure includes two parts: first we should perform BPE on the original files and obtain the `x.input0` files, then we call the `fairseq-preprocess` to process both `x.input0` and `x.label` files to obtain the folder `proc_dataset/tabfact/tapex.large`.
- When we evaluate the model, at first we should call the following interface:
```python
bart = BARTModel.from_pretrained( args.model_dir,  data_name_or_path=args.dataset_dir ) 
```
The recover of the BARTModel requires both the `model_dir` and the `dataset_dir`, where the `model_dir` is used to recover the model weights, while `dataset_dir` is used to recover the tokenizer, which requires the `dict.txt` files. The below hint comments (from your log) are for prompting us that how many tokens does the dictionary have (both 50265 in this case, but we know that for TabFact the output should not be so large):
```
2021-12-02 17:10:44 | INFO | fairseq.tasks.sentence_prediction | [input] dictionary: 50265 types
2021-12-02 17:10:44 | INFO | fairseq.tasks.sentence_prediction | [label] dictionary: 50265 types
```

Don't know if I explain it clearly. Further discussion are warmly welcome!

**Comment by vnik18** [comment]
@SivilTaram Thank you, that makes sense! One last question: what do the tokens `madeupword0000` and `madeupword0001` in the above `dict.txt` file mean?

**Comment by SivilTaram** [comment]
@vnik18 That's a good question! Honestly, I do not know their physical meanings. I personally think they are appended into `dict.txt` because they are somehow default placeholder tokens in the task defined in `fairseq`. You may have a look at the `dict.txt` in `bart.base` or `tapex.base`, then you will find many `madeupwordxxxx`. They are similarly meaningless, which can be replaced with your special token when fine-tuning, just as those `unused` tokens defined by BERT.

**Comment by vnik18** [comment]
@SivilTaram Okay. Thank you very much once again for all your help!
