### ISSUE TITLE
Tapex performance on large tables

### ISSUE THREAD

**Issue by srewai** [microsoft/Table-Pretraining#19]
Hello team, I've csv files with more than 30K rows and 10 columns. I am in need of your help to understand what is the best way to approach this problem since the table is too large. Is Tapex able to handle large tables or there are work around that I can adapt?

The first thought that comes into my mind is splitting the huge table into multiple sub-tables(meaning column names will remain the same) and then perform inference on it. The predictions further can be aggregated for final results.
Could you please share your expertise on this problem. In general, how are the large tableQA performed, please suggest.

Additionally, can we list/view the corresponding SQL queries of predicted answers?

**Comment by SivilTaram** [comment]
@srewai Hi! Thanks for the very interesting question (Yes it is quite challenging). I think the best practise may be using the text-to-SQL parser instead of current text-to-answer models on table/database. Similar to previous works (e.g., TaPaS), TAPEX cannot accommodate large tables since it requires the input table to be linearized as the input for the model. But it is not the case for current text-to-SQL parsers. Therefore, I would recommend you to use [UniSAR](https://github.com/microsoft/ContextualSP/tree/master/unified_parser_text_to_sql) as the backbone to tackle your problem. Hope that helps!

Best,
Qian

**Comment by srewai** [comment]
@SivilTaram , I genuinely appreciate your quick and "right direction approach" help here:). I was also having look at the paper [hybrid ranking by microsoft](https://arxiv.org/pdf/2008.04759.pdf) . This seems promising too. Just a thought if you've any experience with this paper:).

**Comment by SivilTaram** [comment]
@srewai Not yet maybe because it is for WikiSQL haha. But I think it is worthy to have a try on that! Also, I think dense retrieval may be one kind of potential solution :)

**Comment by SivilTaram** [comment]
Closed since no more activity. Feel free to re-open it :)

**Comment by srewai** [comment]
@SivilTaram sorry , i am still infected with covid:/. I had look at the UniSAR paper, looks promising with impressive results. Is this SOTA for text-to-SQL as of now? Or are there any other papers as well that you would suggest. We want to make enterprise level text-to-SQL system. 
-You're amazing, thanks for your help:)
